export const Home = '/'
export const ViewPost = '/posts/:postID'
export const CreatePost = '/posts/create-post'
export const EditPost = '/posts/edit-post/:postID'
export const Dashboard = '/dashboard/:userID'
export const Login = '/login'
export const Signup = '/signup'